---
- type: replace
  path: /releases/-
  value:
    name: "bosh-dns-aliases"
    version: "0.0.3"
    url: "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=0.0.3"
    sha1: "b0d0a0350ed87f1ded58b2ebb469acea0e026ccc"

- type: replace
  path: /instance_groups/name=uaaproxy/jobs/name=bosh-dns-aliases?/release
  value: bosh-dns-aliases

- type: replace
  path: /instance_groups/name=uaaproxy/jobs/name=bosh-dns-aliases?/properties?/aliases?/-
  value:
    # use bosh-dns, point domain to mattermost target
    domain: mattermost.cf.internal
    targets:
      - deployment: mattermost
        domain: bosh
        instance_group: mattermost
        network: default
        query: '*'

- type: replace
  path: /instance_groups/name=uaaproxy/jobs/name=bosh-dns-aliases/properties/aliases/-
  value:
    # use bosh-dns, point domain to uaa target
    domain: uaa.service.cf.internal
    targets:
      - deployment: uaa
        domain: bosh
        instance_group: uaa
        network: default
        query: '*'
